added screens and navigation
MarkoDubravac/android-vjestina-tmdb pull request #2
Opened 2022-11-16 21:33 UTC by MarkoDubravac

![315890443_1111498609734333_2329589106461029548_n](https://user-images.githubusercontent.com/73428201/202299051-a50744d5-f5ac-4343-b1ef-8c5736cf0724.jpg)
![314397628_816737679538572_5789592484980526344_n](https://user-images.githubusercontent.com/73428201/202299082-45b9de94-ce0b-4943-a238-58929f0abd70.jpg)
![315480063_3255617614766707_8621430367014201341_n](https://user-images.githubusercontent.com/73428201/202299085-1a3c3be9-7cfa-4c8a-9e1d-5856c6dbdbaf.jpg)

2022-11-23 15:02 UTC, anvukelic requested changes

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/component/FavoriteButton.kt
> +    modifier: Modifier = Modifier,
if you have lambda as a parameter, put it in the last place

This is the correct order

Mandatory properties (fields or lambda parameters)
Optional properties (properties with default values) - Modifier always first
Lambda

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/component/MovieCard.kt
>      modifier: Modifier = Modifier,
use correct order of parameters

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/favorites/FavoritesScreen.kt
> +    LazyVerticalGrid(modifier = modifier.padding(MaterialTheme.spacing.small),
formatting
modifier in the new line and then reformat code

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/favorites/mapper/FavoritesMapperImpl.kt
> +
redundant empty line

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/favorites/mapper/FavoritesMapperImpl.kt
> +        return FavoritesViewState(favoriteMovies = favoriteMovies.map { toFavoritesMovieViewState(it) })
expression function

check this https://stackoverflow.com/questions/64856717/kotlin-expression-fun-vs-normal-fun-differences

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/favorites/mapper/FavoritesMapperImpl.kt
> +        return FavoritesMovieViewState(
expression function

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeScreen.kt
> +    onNavigateToMovieDetails: (Int) -> Unit,
oneliner

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeScreen.kt
> +        modifier = modifier.padding(MaterialTheme.spacing.small),
formatting

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeScreen.kt
> +            text = title, style = Typography.h3
formatting

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/home/mapper/HomeScreenMapperImpl.kt
> +        return HomeMovieCategoryViewState(
expression fun

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/home/mapper/HomeScreenMapperImpl.kt
> +        return HomeMovieViewState(
expression fun

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/home/mapper/HomeScreenMapperImpl.kt
> +        return MovieCategoryLabelViewState(
expression fun

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/home/mapper/HomeScreenMapperImpl.kt
> +
redundant empty lines

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +    var showBottomBar by remember {
oneline

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +private fun TopBar(
oneliner

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +        backgroundColor = MaterialTheme.colors.background
oneliner

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +                Column(
oneliner

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +                                    onNavigateToDestination(destination)
oneliner

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +        movieDetailsViewState = movieDetailsViewState.copy(isFavorite = !movieDetailsViewState.isFavorite),
oneliner

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +        item {
oneliner

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +        item {
oneliner

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +        modifier = modifier.padding(MaterialTheme.spacing.small),
oneliner

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +        modifier = modifier.padding(MaterialTheme.spacing.small),
oneliner

2022-11-23 15:02 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/mapper/MovieDetailsMapperImpl.kt
> +class MovieDetailsMapperImpl : MovieDetailsMapper {
expression functions

2022-11-26 21:01 UTC, MarkoDubravac commented
Im sorry, is there any setting I should change to fix one liners in the future? Im currently using default kotlin style.
![image](https://user-images.githubusercontent.com/73428201/204108760-8adeb18c-cbc1-4a61-8645-691dc146ebe7.png)

2022-11-29 21:29 UTC, anvukelic approved these changes

2022-11-30 12:41 UTC, anvukelic requested changes

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/favorites/FavoritesScreen.kt
> +fun FavoritesRoute(
oneliner

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeScreen.kt
> +    onNavigateToMovieDetails: (
onNavigateToMovieDetails should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeScreen.kt
> +    onCategoryClick: (
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeScreen.kt
> +    onNavigateToMovieDetails: (
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeScreen.kt
> +    LazyColumn(
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeScreen.kt
> +    onCategoryClick: (
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeScreen.kt
> +    onNavigateToMovieDetails: (
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeScreen.kt
> +        modifier = modifier.padding(
Column and Modifier, both can be fitted in one line - modifier is in one line only if you use only one modifier on it

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeScreen.kt
> +            horizontalArrangement = Arrangement.spacedBy(
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeScreen.kt
> +            horizontalArrangement = Arrangement.spacedBy(
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +    var showBottomBar by remember {
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +                navigationIcon = {
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +                        navArgument(MOVIE_ID_KEY) {
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +                dimensionResource(
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +            painter = painterResource(
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +            modifier = Modifier.align(
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +        painter = painterResource(
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +        contentDescription = stringResource(
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +            .clickable {
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +            .size(
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +    onNavigateToDestination: (
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +    BottomNavigation(
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +                .padding(
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +                                .clickable {
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +                        text = stringResource(
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +                        .align(
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +        modifier = modifier.padding(
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +            modifier = Modifier.height(
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +            horizontalArrangement = Arrangement.spacedBy(
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +            verticalArrangement = Arrangement.spacedBy(
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +                    CrewItem(
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +        modifier = modifier.padding(
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +            contentPadding = PaddingValues(
should be in one line

2022-11-30 12:41 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/moviedetails/MovieDetailsScreen.kt
> +            horizontalArrangement = Arrangement.spacedBy(
should be in one line

2022-12-05 09:58 UTC, anvukelic approved these changes

2022-12-05 09:58 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/favorites/FavoritesScreen.kt
> +fun FavoritesRoute(
?

2022-12-05 09:58 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/home/HomeScreen.kt
> +    onNavigateToMovieDetails: (Int) -> Unit,
this one is not resolved

2022-12-05 09:58 UTC, anvukelic commented on android-vjestina-homework-movie-app-data-mock/app/src/main/java/agency/five/codebase/android/movieapp/ui/main/MainScreen.kt
> +                Column(
not resolved

2022-12-09 08:32 UTC, anvukelic approved these changes

2022-12-09 17:04 UTC, merged